In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('/content/creditcard.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
X = df.drop('Class',axis=1)
y = df['Class']

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
tree = DecisionTreeClassifier(max_depth= 5, random_state=42)
knn = KNeighborsClassifier(n_neighbors =3)
svc = SVC()
treeforest= RandomForestClassifier(n_estimators=100,random_state=42)


tree.fit(X_train,y_train)
knn.fit(X_train,y_train)
svc.fit(X_train,y_train)
treeforest.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [8]:
y_tree = tree.predict(X_test)
knn_pred = knn.predict(X_test)
svc_pred = svc.predict(X_test)
treeforest_pred = treeforest.predict(X_test)

In [10]:
print(accuracy_score(y_test,y_tree))
print(accuracy_score(y_test,knn_pred))
print(accuracy_score(y_test,svc_pred))
print(accuracy_score(y_test,treeforest_pred))

0.9994908886626171
0.9984375548611355
0.9982795547909132
0.9995611109160493

In [11]:
df['Time'].unique()

array([0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 1.72787e+05,
       1.72788e+05, 1.72792e+05])

In [12]:
for i in df['Time'].unique():
  print(i)

Streaming output truncated to the last 5000 lines.
166355.0
166357.0
166358.0
166359.0
166360.0
166361.0
166362.0
166363.0
166364.0
166365.0
166366.0
166367.0
166368.0
166369.0
166370.0
166371.0
166372.0
166373.0
166374.0
166375.0
166376.0
166378.0
166379.0
166380.0
166381.0
166383.0
166384.0
166385.0
166386.0
166387.0
166388.0
166389.0
166390.0
166391.0
166392.0
166393.0
166394.0
166395.0
166396.0
166397.0
166398.0
166399.0
166401.0
166402.0
166403.0
166404.0
166405.0
166406.0
166407.0
166408.0
166409.0
166410.0
166411.0
166412.0
166413.0
166414.0
166415.0
166416.0
166417.0
166418.0
166419.0
166420.0
166421.0
166422.0
166423.0
166424.0
166425.0
166426.0
166427.0
166428.0
166429.0
166431.0
166432.0
166433.0
166435.0
166436.0
166437.0
166438.0
166439.0
166440.0
166441.0
166442.0
166443.0
166445.0
166446.0
166447.0
166450.0
166451.0
166452.0
166453.0
166454.0
166455.0
166456.0
166458.0
166459.0
166461.0
166462.0
166463.0
166464.0
166465.0
166467.0
166468.0
166469.0
166470.0
166471.0
166472.0
166473.0
166474.0
166475.0
166476.0
166477.0
166478.0
166479.0
166480.0
166481.0
166482.0
166483.0
166484.0
166485.0
166486.0
166487.0
166488.0
166489.0
166490.0
166491.0
166492.0
166493.0
166494.0
166495.0
166496.0
166497.0
166498.0
166499.0
166500.0
166501.0
166502.0
166503.0
166504.0
166505.0
166506.0
166508.0
166509.0
166510.0
166511.0
166512.0
166513.0
166514.0
166515.0
166516.0
166518.0
166519.0
166520.0
166521.0
166522.0
166523.0
166524.0
166526.0
166527.0
166528.0
166529.0
166530.0
166531.0
166532.0
166533.0
166534.0
166535.0
166536.0
166537.0
166538.0
166539.0
166540.0
166542.0
166543.0
166544.0
166545.0
166546.0
166548.0
166549.0
166550.0
166551.0
166552.0
166553.0
166555.0
166556.0
166558.0
166559.0
166560.0
166561.0
166562.0
166564.0
166566.0
166567.0
166568.0
166569.0
166570.0
166571.0
166572.0
166573.0
166574.0
166575.0
166576.0
166577.0
166578.0
166579.0
166580.0
166582.0
166583.0
166585.0
166586.0
166587.0
166589.0
166590.0
166591.0
166593.0
166594.0
166595.0
166596.0
166597.0
166598.0
166599.0
166600.0
166601.0
166602.0
166604.0
166605.0
166607.0
166608.0
166609.0
166610.0
166611.0
166613.0
166614.0
166615.0
166617.0
166618.0
166619.0
166620.0
166621.0
166622.0
166623.0
166625.0
166626.0
166627.0
166628.0
166629.0
166630.0
166632.0
166633.0
166634.0
166636.0
166637.0
166639.0
166640.0
166641.0
166642.0
166643.0
166644.0
166645.0
166646.0
166647.0
166649.0
166650.0
166651.0
166652.0
166653.0
166654.0
166656.0
166658.0
166659.0
166661.0
166663.0
166664.0
166665.0
166666.0
166667.0
166668.0
166669.0
166671.0
166673.0
166674.0
166676.0
166677.0
166678.0
166679.0
166680.0
166681.0
166683.0
166684.0
166685.0
166686.0
166687.0
166688.0
166689.0
166690.0
166691.0
166692.0
166694.0
166695.0
166696.0
166697.0
166698.0
166699.0
166700.0
166701.0
166702.0
166703.0
166704.0
166705.0
166706.0
166707.0
166708.0
166709.0
166712.0
166714.0
166715.0
166716.0
166718.0
166719.0
166720.0
166721.0
166722.0
166723.0
166724.0
166725.0
166726.0
166728.0
166729.0
166730.0
166733.0
166734.0
166735.0
166737.0
166738.0
166739.0
166740.0
166742.0
166743.0
166744.0
166745.0
166746.0
166748.0
166749.0
166751.0
166752.0
166753.0
166754.0
166755.0
166756.0
166757.0
166758.0
166759.0
166760.0
166761.0
166762.0
166763.0
166764.0
166765.0
166766.0
166767.0
166768.0
166769.0
166770.0
166771.0
166772.0
166773.0
166774.0
166775.0
166776.0
166777.0
166778.0
166779.0
166780.0
166781.0
166782.0
166784.0
166786.0
166787.0
166788.0
166789.0
166790.0
166791.0
166792.0
166793.0
166795.0
166796.0
166797.0
166798.0
166799.0
166802.0
166803.0
166804.0
166805.0
166806.0
166807.0
166808.0
166809.0
166810.0
166811.0
166812.0
166814.0
166815.0
166816.0
166817.0
166818.0
166819.0
166821.0
166822.0
166824.0
166825.0
166826.0
166827.0
166828.0
166829.0
166831.0
166833.0
166835.0
166837.0
166839.0
166841.0
166842.0
166843.0
166845.0
166846.0
166847.0
166848.0
166849.0
166850.0
166852.0
166853.0
166854.0
166855.0
166856.0
166857.0
166858.0
166859.0
166861.0
166862.0
166863.0
166864.0
166865.0
166866.0
166867.0
166868.0
166869.0
166870.0
166871.0
166872.0
166873.0
166875.0
166877.0
166878.0
166879.0
166880.0
166882.0
166883.0
166884.0
166885.0
166886.0
166887.0
166888.0
166889.0
166890.0
166891.0
166893.0
166894.0
166898.0
166899.0
166901.0
166902.0
166903.0
166905.0
166906.0
166907.0
166908.0
166909.0
166910.0
166911.0
166913.0
166914.0
166915.0
166916.0
166917.0
166918.0
166919.0
166920.0
166921.0
166922.0
166923.0
166924.0
166925.0
166926.0
166927.0
166929.0
166930.0
166931.0
166932.0
166933.0
166935.0
166936.0
166937.0
166938.0
166939.0
166940.0
166941.0
166942.0
166943.0
166944.0
166945.0
166946.0
166947.0
166948.0
166949.0
166950.0
166951.0
166952.0
166954.0
166955.0
166957.0
166960.0
166961.0
166962.0
166963.0
166964.0
166966.0
166967.0
166968.0
166969.0
166970.0
166971.0
166972.0
166973.0
166974.0
166975.0
166977.0
166979.0
166980.0
166981.0
166983.0
166986.0
166987.0
166988.0
166989.0
166990.0
166991.0
166992.0
166993.0
166995.0
166996.0
166997.0
166998.0
166999.0
167000.0
167001.0
167003.0
167004.0
167006.0
167007.0
167008.0
167009.0
167010.0
167011.0
167013.0
167014.0
167015.0
167016.0
167017.0
167018.0
167019.0
167022.0
167023.0
167024.0
167025.0
167026.0
167028.0
167029.0
167030.0
167031.0
167032.0
167033.0
167034.0
167035.0
167036.0
167037.0
167038.0
167039.0
167041.0
167042.0
167043.0
167045.0
167047.0
167048.0
167049.0
167050.0
167052.0
167053.0
167054.0
167055.0
167057.0
167059.0
167060.0
167061.0
167063.0
167064.0
167065.0
167066.0
167067.0
167068.0
167069.0
167070.0
167072.0
167073.0
167074.0
167075.0
167076.0
167077.0
167078.0
167080.0
167081.0
167082.0
167083.0
167086.0
167088.0
167089.0
167090.0
167091.0
167092.0
167093.0
167094.0
167095.0
167096.0
167098.0
167101.0
167102.0
167103.0
167104.0
167105.0
167107.0
167109.0
167110.0
167111.0
167112.0
167113.0
167114.0
167115.0
167116.0
167120.0
167121.0
167122.0
167123.0
167125.0
167126.0
167127.0
167129.0
167131.0
167132.0
167133.0
167134.0
167135.0
167137.0
167138.0
167139.0
167141.0
167142.0
167143.0
167144.0
167145.0
167146.0
167148.0
167149.0
167150.0
167152.0
167153.0
167154.0
167155.0
167156.0
167157.0
167158.0
167159.0
167161.0
167162.0
167164.0
167165.0
167166.0
167167.0
167169.0
167170.0
167171.0
167172.0
167173.0
167174.0
167175.0
167176.0
167177.0
167178.0
167179.0
167180.0
167181.0
167182.0
167183.0
167185.0
167188.0
167189.0
167190.0
167191.0
167192.0
167193.0
167195.0
167198.0
167199.0
167201.0
167203.0
167204.0
167205.0
167206.0
167207.0
167208.0
167209.0
167211.0
167212.0
167213.0
167214.0
167215.0
167216.0
167217.0
167219.0
167221.0
167222.0
167223.0
167224.0
167225.0
167226.0
167227.0
167228.0
167229.0
167231.0
167232.0
167233.0
167234.0
167235.0
167236.0
167237.0
167238.0
167240.0
167241.0
167242.0
167243.0
167244.0
167245.0
167246.0
167247.0
167248.0
167249.0
167250.0
167251.0
167252.0
167253.0
167254.0
167255.0
167257.0
167258.0
167259.0
167261.0
167262.0
167263.0
167264.0
167265.0
167266.0
167267.0
167268.0
167269.0
167270.0
167271.0
167272.0
167273.0
167274.0
167275.0
167276.0
167277.0
167278.0
167280.0
167283.0
167284.0
167285.0
167287.0
167288.0
167289.0
167290.0
167291.0
167292.0
167293.0
167294.0
167296.0
167297.0
167298.0
167299.0
167300.0
167301.0
167302.0
167303.0
167304.0
167305.0
167306.0
167307.0
167308.0
167309.0
167310.0
167311.0
167312.0
167313.0
167314.0
167315.0
167316.0
167317.0
167318.0
167319.0
167321.0
167322.0
167323.0
167324.0
167325.0
167326.0
167327.0
167328.0
167329.0
167330.0
167331.0
167332.0
167333.0
167334.0
167335.0
167338.0
167339.0
167341.0
167342.0
167343.0
167344.0
167345.0
167346.0
167347.0
167348.0
167349.0
167350.0
167351.0
167352.0
167354.0
167356.0
167357.0
167358.0
167359.0
167360.0
167361.0
167362.0
167363.0
167364.0
167365.0
167366.0
167368.0
167369.0
167370.0
167371.0
167372.0
167373.0
167374.0
167376.0
167377.0
167378.0
167379.0
167380.0
167381.0
167382.0
167383.0
167384.0
167385.0
167386.0
167387.0
167388.0
167389.0
167390.0
167391.0
167392.0
167394.0
167395.0
167396.0
167397.0
167398.0
167399.0
167400.0
167401.0
167402.0
167403.0
167404.0
167406.0
167407.0
167408.0
167410.0
167411.0
167412.0
167414.0
167417.0
167418.0
167422.0
167424.0
167425.0
167426.0
167427.0
167430.0
167431.0
167432.0
167434.0
167435.0
167436.0
167437.0
167439.0
167441.0
167442.0
167443.0
167444.0
167445.0
167446.0
167447.0
167448.0
167449.0
167450.0
167451.0
167452.0
167455.0
167456.0
167457.0
167458.0
167459.0
167460.0
167461.0
167462.0
167463.0
167464.0
167465.0
167466.0
167467.0
167468.0
167469.0
167471.0
167472.0
167473.0
167474.0
167475.0
167476.0
167477.0
167478.0
167479.0
167482.0
167483.0
167484.0
167485.0
167486.0
167487.0
167488.0
167489.0
167490.0
167491.0
167492.0
167493.0
167494.0
167495.0
167496.0
167497.0
167499.0
167500.0
167501.0
167502.0
167504.0
167506.0
167507.0
167508.0
167510.0
167511.0
167512.0
167513.0
167514.0
167515.0
167516.0
167517.0
167518.0
167519.0
167520.0
167521.0
167522.0
167523.0
167524.0
167526.0
167528.0
167529.0
167530.0
167531.0
167532.0
167534.0
167535.0
167536.0
167537.0
167538.0
167539.0
167540.0
167541.0
167543.0
167545.0
167546.0
167548.0
167549.0
167550.0
167552.0
167553.0
167554.0
167556.0
167557.0
167558.0
167559.0
167560.0
167561.0
167562.0
167563.0
167564.0
167566.0
167567.0
167568.0
167569.0
167570.0
167572.0
167573.0
167575.0
167576.0
167577.0
167578.0
167580.0
167581.0
167582.0
167583.0
167584.0
167585.0
167586.0
167588.0
167589.0
167591.0
167592.0
167593.0
167594.0
167595.0
167596.0
167597.0
167598.0
167599.0
167600.0
167601.0
167602.0
167603.0
167604.0
167605.0
167606.0
167607.0
167608.0
167609.0
167610.0
167611.0
167612.0
167613.0
167614.0
167615.0
167616.0
167618.0
167619.0
167620.0
167621.0
167622.0
167624.0
167625.0
167626.0
167627.0
167628.0
167629.0
167630.0
167631.0
167632.0
167633.0
167636.0
167638.0
167639.0
167642.0
167643.0
167644.0
167646.0
167647.0
167648.0
167649.0
167650.0
167651.0
167653.0
167654.0
167655.0
167656.0
167657.0
167658.0
167659.0
167661.0
167662.0
167663.0
167664.0
167665.0
167666.0
167667.0
167668.0
167669.0
167670.0
167672.0
167673.0
167674.0
167675.0
167676.0
167677.0
167678.0
167679.0
167680.0
167681.0
167682.0
167683.0
167684.0
167685.0
167686.0
167687.0
167688.0
167689.0
167690.0
167691.0
167692.0
167693.0
167694.0
167695.0
167696.0
167697.0
167698.0
167699.0
167700.0
167702.0
167703.0
167704.0
167705.0
167707.0
167709.0
167710.0
167711.0
167712.0
167713.0
167714.0
167715.0
167716.0
167717.0
167718.0
167719.0
167720.0
167721.0
167722.0
167723.0
167724.0
167725.0
167726.0
167727.0
167728.0
167729.0
167731.0
167732.0
167733.0
167734.0
167735.0
167737.0
167739.0
167740.0
167741.0
167742.0
167744.0
167745.0
167748.0
167749.0
167750.0
167751.0
167752.0
167753.0
167754.0
167755.0
167756.0
167758.0
167759.0
167761.0
167762.0
167763.0
167764.0
167765.0
167766.0
167767.0
167768.0
167770.0
167771.0
167772.0
167774.0
167775.0
167778.0
167779.0
167781.0
167782.0
167784.0
167785.0
167787.0
167788.0
167789.0
167791.0
167792.0
167793.0
167794.0
167795.0
167797.0
167798.0
167800.0
167801.0
167802.0
167803.0
167804.0
167805.0
167806.0
167808.0
167809.0
167810.0
167811.0
167812.0
167813.0
167814.0
167815.0
167816.0
167817.0
167818.0
167819.0
167820.0
167821.0
167822.0
167823.0
167825.0
167826.0
167827.0
167828.0
167829.0
167830.0
167831.0
167833.0
167834.0
167835.0
167837.0
167838.0
167840.0
167842.0
167843.0
167844.0
167845.0
167846.0
167847.0
167848.0
167849.0
167850.0
167853.0
167854.0
167855.0
167856.0
167858.0
167859.0
167860.0
167861.0
167862.0
167864.0
167866.0
167867.0
167868.0
167870.0
167871.0
167872.0
167873.0
167874.0
167876.0
167877.0
167878.0
167879.0
167880.0
167881.0
167882.0
167883.0
167884.0
167885.0
167886.0
167887.0
167888.0
167889.0
167890.0
167891.0
167892.0
167893.0
167894.0
167897.0
167899.0
167900.0
167901.0
167902.0
167904.0
167906.0
167907.0
167908.0
167909.0
167910.0
167911.0
167912.0
167913.0
167914.0
167916.0
167917.0
167919.0
167920.0
167921.0
167922.0
167923.0
167924.0
167925.0
167927.0
167928.0
167929.0
167930.0
167932.0
167933.0
167934.0
167935.0
167936.0
167937.0
167938.0
167939.0
167940.0
167941.0
167943.0
167944.0
167945.0
167946.0
167947.0
167949.0
167950.0
167951.0
167953.0
167954.0
167956.0
167957.0
167959.0
167960.0
167961.0
167962.0
167963.0
167964.0
167965.0
167967.0
167968.0
167969.0
167970.0
167971.0
167972.0
167973.0
167974.0
167975.0
167976.0
167978.0
167980.0
167981.0
167982.0
167983.0
167984.0
167986.0
167987.0
167988.0
167989.0
167991.0
167992.0
167993.0
167994.0
167995.0
167996.0
167998.0
167999.0
168000.0
168002.0
168004.0
168006.0
168007.0
168008.0
168009.0
168010.0
168011.0
168013.0
168014.0
168016.0
168017.0
168018.0
168019.0
168020.0
168021.0
168022.0
168023.0
168024.0
168025.0
168026.0
168027.0
168028.0
168030.0
168031.0
168033.0
168034.0
168035.0
168036.0
168037.0
168038.0
168039.0
168040.0
168041.0
168042.0
168043.0
168046.0
168047.0
168048.0
168049.0
168050.0
168051.0
168052.0
168053.0
168055.0
168057.0
168058.0
168059.0
168060.0
168061.0
168062.0
168063.0
168065.0
168066.0
168067.0
168068.0
168069.0
168070.0
168072.0
168073.0
168075.0
168076.0
168077.0
168079.0
168080.0
168082.0
168083.0
168084.0
168085.0
168086.0
168088.0
168089.0
168090.0
168091.0
168092.0
168093.0
168094.0
168096.0
168097.0
168099.0
168100.0
168101.0
168102.0
168104.0
168105.0
168106.0
168107.0
168108.0
168109.0
168111.0
168112.0
168113.0
168114.0
168115.0
168116.0
168117.0
168119.0
168120.0
168121.0
168123.0
168125.0
168126.0
168127.0
168129.0
168130.0
168131.0
168132.0
168134.0
168135.0
168137.0
168138.0
168140.0
168143.0
168144.0
168145.0
168146.0
168147.0
168148.0
168150.0
168151.0
168152.0
168153.0
168154.0
168155.0
168156.0
168157.0
168158.0
168159.0
168160.0
168161.0
168162.0
168163.0
168164.0
168165.0
168166.0
168168.0
168169.0
168171.0
168172.0
168173.0
168174.0
168175.0
168176.0
168177.0
168178.0
168179.0
168180.0
168182.0
168183.0
168184.0
168185.0
168190.0
168191.0
168192.0
168193.0
168194.0
168196.0
168197.0
168199.0
168200.0
168201.0
168202.0
168203.0
168205.0
168206.0
168207.0
168209.0
168210.0
168211.0
168212.0
168213.0
168214.0
168217.0
168219.0
168220.0
168221.0
168222.0
168223.0
168224.0
168226.0
168227.0
168228.0
168229.0
168230.0
168231.0
168232.0
168233.0
168235.0
168236.0
168237.0
168238.0
168239.0
168240.0
168241.0
168242.0
168243.0
168244.0
168245.0
168246.0
168248.0
168250.0
168252.0
168254.0
168255.0
168256.0
168257.0
168258.0
168260.0
168261.0
168262.0
168267.0
168269.0
168270.0
168272.0
168274.0
168275.0
168276.0
168277.0
168279.0
168280.0
168281.0
168282.0
168283.0
168284.0
168285.0
168286.0
168287.0
168289.0
168290.0
168291.0
168292.0
168293.0
168295.0
168296.0
168297.0
168298.0
168300.0
168301.0
168302.0
168303.0
168304.0
168305.0
168306.0
168307.0
168308.0
168310.0
168312.0
168314.0
168315.0
168316.0
168317.0
168318.0
168319.0
168320.0
168321.0
168322.0
168323.0
168324.0
168325.0
168327.0
168328.0
168329.0
168331.0
168332.0
168333.0
168334.0
168335.0
168336.0
168337.0
168338.0
168339.0
168342.0
168343.0
168344.0
168345.0
168347.0
168348.0
168349.0
168350.0
168351.0
168355.0
168356.0
168357.0
168358.0
168360.0
168362.0
168363.0
168364.0
168365.0
168366.0
168367.0
168368.0
168369.0
168370.0
168371.0
168372.0
168373.0
168374.0
168375.0
168376.0
168377.0
168378.0
168381.0
168382.0
168383.0
168384.0
168385.0
168387.0
168388.0
168390.0
168393.0
168394.0
168395.0
168396.0
168397.0
168398.0
168399.0
168400.0
168401.0
168402.0
168403.0
168405.0
168406.0
168407.0
168408.0
168409.0
168410.0
168411.0
168412.0
168414.0
168415.0
168417.0
168418.0
168419.0
168420.0
168421.0
168422.0
168423.0
168424.0
168425.0
168426.0
168427.0
168428.0
168429.0
168430.0
168431.0
168432.0
168433.0
168435.0
168436.0
168438.0
168439.0
168442.0
168443.0
168444.0
168445.0
168447.0
168449.0
168451.0
168452.0
168453.0
168454.0
168455.0
168456.0
168457.0
168459.0
168460.0
168461.0
168462.0
168463.0
168464.0
168465.0
168466.0
168468.0
168469.0
168470.0
168471.0
168472.0
168473.0
168474.0
168475.0
168476.0
168477.0
168478.0
168479.0
168481.0
168483.0
168484.0
168485.0
168487.0
168488.0
168490.0
168491.0
168492.0
168493.0
168495.0
168497.0
168498.0
168499.0
168500.0
168501.0
168504.0
168505.0
168506.0
168507.0
168508.0
168509.0
168510.0
168511.0
168512.0
168513.0
168514.0
168516.0
168517.0
168519.0
168520.0
168522.0
168523.0
168524.0
168525.0
168526.0
168527.0
168529.0
168530.0
168531.0
168532.0
168533.0
168534.0
168535.0
168538.0
168539.0
168540.0
168543.0
168544.0
168545.0
168548.0
168549.0
168551.0
168552.0
168553.0
168554.0
168556.0
168557.0
168558.0
168559.0
168560.0
168561.0
168562.0
168563.0
168565.0
168566.0
168567.0
168568.0
168569.0
168570.0
168571.0
168572.0
168573.0
168574.0
168575.0
168576.0
168577.0
168580.0
168583.0
168584.0
168585.0
168586.0
168587.0
168588.0
168589.0
168590.0
168591.0
168592.0
168594.0
168595.0
168597.0
168598.0
168599.0
168600.0
168601.0
168603.0
168604.0
168605.0
168606.0
168608.0
168610.0
168611.0
168612.0
168613.0
168614.0
168615.0
168616.0
168617.0
168619.0
168621.0
168622.0
168623.0
168624.0
168625.0
168626.0
168627.0
168628.0
168629.0
168630.0
168633.0
168634.0
168636.0
168637.0
168638.0
168639.0
168641.0
168645.0
168646.0
168647.0
168648.0
168649.0
168650.0
168651.0
168652.0
168653.0
168654.0
168655.0
168657.0
168658.0
168659.0
168660.0
168662.0
168663.0
168664.0
168665.0
168667.0
168668.0
168670.0
168671.0
168672.0
168674.0
168675.0
168676.0
168677.0
168678.0
168679.0
168680.0
168681.0
168682.0
168683.0
168684.0
168685.0
168686.0
168687.0
168688.0
168689.0
168691.0
168693.0
168695.0
168697.0
168698.0
168699.0
168700.0
168701.0
168702.0
168703.0
168704.0
168706.0
168707.0
168708.0
168709.0
168711.0
168714.0
168715.0
168716.0
168717.0
168718.0
168719.0
168720.0
168721.0
168723.0
168725.0
168726.0
168728.0
168729.0
168731.0
168732.0
168733.0
168734.0
168735.0
168736.0
168737.0
168738.0
168739.0
168740.0
168741.0
168742.0
168743.0
168745.0
168747.0
168748.0
168749.0
168751.0
168752.0
168753.0
168754.0
168755.0
168757.0
168758.0
168759.0
168760.0
168761.0
168762.0
168763.0
168766.0
168767.0
168768.0
168769.0
168771.0
168772.0
168773.0
168774.0
168775.0
168776.0
168777.0
168779.0
168780.0
168781.0
168783.0
168784.0
168785.0
168786.0
168787.0
168788.0
168789.0
168790.0
168792.0
168794.0
168795.0
168796.0
168798.0
168799.0
168800.0
168801.0
168802.0
168806.0
168807.0
168808.0
168809.0
168810.0
168811.0
168814.0
168815.0
168816.0
168817.0
168819.0
168820.0
168821.0
168822.0
168823.0
168825.0
168826.0
168827.0
168828.0
168829.0
168830.0
168831.0
168833.0
168834.0
168835.0
168836.0
168837.0
168838.0
168839.0
168840.0
168843.0
168845.0
168846.0
168847.0
168848.0
168849.0
168850.0
168852.0
168853.0
168854.0
168855.0
168857.0
168858.0
168859.0
168860.0
168861.0
168862.0
168863.0
168864.0
168865.0
168866.0
168867.0
168868.0
168869.0
168870.0
168871.0
168872.0
168875.0
168876.0
168877.0
168879.0
168880.0
168881.0
168882.0
168884.0
168885.0
168886.0
168887.0
168888.0
168889.0
168890.0
168891.0
168892.0
168893.0
168895.0
168896.0
168898.0
168899.0
168901.0
168902.0
168906.0
168907.0
168908.0
168909.0
168910.0
168911.0
168912.0
168913.0
168914.0
168916.0
168917.0
168918.0
168919.0
168921.0
168923.0
168924.0
168925.0
168926.0
168927.0
168928.0
168929.0
168930.0
168931.0
168933.0
168935.0
168936.0
168937.0
168938.0
168939.0
168940.0
168941.0
168942.0
168943.0
168944.0
168945.0
168946.0
168949.0
168950.0
168953.0
168955.0
168956.0
168957.0
168959.0
168962.0
168964.0
168965.0
168969.0
168970.0
168971.0
168973.0
168974.0
168975.0
168976.0
168978.0
168979.0
168980.0
168981.0
168984.0
168985.0
168987.0
168988.0
168989.0
168990.0
168991.0
168992.0
168993.0
168994.0
168996.0
168998.0
169000.0
169001.0
169002.0
169004.0
169005.0
169006.0
169009.0
169010.0
169011.0
169013.0
169015.0
169016.0
169017.0
169018.0
169019.0
169020.0
169021.0
169023.0
169024.0
169026.0
169027.0
169028.0
169029.0
169031.0
169032.0
169034.0
169035.0
169036.0
169037.0
169038.0
169039.0
169040.0
169041.0
169042.0
169043.0
169044.0
169045.0
169046.0
169048.0
169050.0
169051.0
169053.0

In [14]:
xgboost = XGBClassifier(max_depth=4, n_estimators=200, learning_rate=0.1,
        use_label_encoder=False,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1)
xgboost.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [13:23:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=-1,
              num_parallel_tree=None, ...)

In [15]:
xgb_pred = xgboost.predict(X_test)
print(accuracy_score(y_test,xgb_pred))

0.9996137776061234